### PR TITLE
93 filenames added

### PR DESCRIPTION
**Pull request by secaproject**
All hashes on chunk2 and chunk4 are complete.

### CODE REVIEW

**Comment by Atvaark** [comment]
Remove the first 2 characters in the first line.

**Comment by secaproject** [comment]
I think now it's ok

**Comment by secaproject** [comment]
New file updated with more than 500 files.

**Comment by secaproject** [comment]
There is an error, i don't added the olders filenames, i'm solving it right now

**Comment by secaproject** [comment]
Fixed

**Comment by secaproject** [comment]
Recount:
Total filenames: 42163
Found: 29140
Unknown: 673
Average: 69.11%

**Comment by secaproject** [comment]
Big update with textures names soon.

**Comment by emoose** [comment]
Nice work so far, I'm happy to merge whenever you are, just give the word :)

Also I noticed there are some filenames which don't seem to be used in the PC data files, eg. "/Assets/mgo/level_asset/player/ParameterTables/AppealActions", I'm guessing these are from the console files? I really need to update my console hashlists..

**Comment by secaproject** [comment]
Hi, I see a lot of files that don't work on PC hashes, so i guess it's for some console files. I don't have the console files to check it out, but if I can help you in anyway, you can say it.

And thanks to you to start this project ;P

**Pull request merged**
