### PR TITLE
dictionary resort and texture update

### PR DESCRIPTION
**Pull request by cstBipBop**
~480 additions over current dictionary and sorted the file after running a duplicate/whitespace removal script.

### CODE REVIEW

**Comment by cstBipBop** [comment]
Fixed conflicts with fork. Added some more texture entries.

**Comment by Polly44** [comment]
I've tried out cstBipBop's dictionary, Emoose's and combined both; but I do not get near the numbers posted in your repository (or cstBipBop's). Would you/anyone be so kind to direct me to the 'most_complete/recent' dictionary? thx in advance.

**Comment by cstBipBop** [comment]
If you're referring to the statistics stuff in the readme, I don't think anyone has updated that. Anyway mine would be the most recent one. It should be something like 5100 entries over Emoose's last pull.

**Comment by Polly44** [comment]
apparently, emoose still refers to the 'old' dict, even though updates are mentioned under 'commits'. Short version: got your updates now as well (combined with emouse and my own). I will be posting this dict shortly on Nexusmods. ps: I do not know how you obtained the additional entries, but I have been trying to 'scan the exe memory' - in particular - for [Database] entries (such as animals, plants, etc). If you have an idea/suggestion, please let me know... Must be of the form such as [/Assets/tpp/ui/texture/Manual/%s/%s/%s/game_manual%02u.ftex] . I've got plenty of these entries: if you are interested in the full list (and are on Xentax), mail to paul44. ps2: I've also sent a request to Sergeanur about the mgo\texture crash (it might be a small thing to fix ~ fingers crossed)

**Comment by cstBipBop** [comment]
Sure I'm CantStoptheBipBop on that site. If you check the MGSV thread on Xentax, one of the recent posts by me explains it in more detail. Basically I brute-forced the entries with a lua script and unknown123's path hasher to check if a generated filepath matched any of the undefined hashes, and the matches get appended to the bottom of the dictionary.

Thanks for the format on database VIs. I might be able to figure some the paths from that. I'll upload the lua script when I get some time to clean it up.

**Comment by emoose** [comment]
Nice work! Sorry for not merging this in sooner, haven't really had much free time.

Just did a recount though and we're now 73.33% named (compared to 62.29% from the last recount) 👍 

Will merge this in and update the readme now, thanks!

**Comment by cstBipBop** [comment]
Cool, and no worries. I've been too busy to really do anything with the game lately so I understand.

**Pull request merged**
